cd openwrt
        rm -f ./.config*
        touch ./.config

        #
        # ================  合并后的 .config（基于原 YAML + config.txt 的 Wi‑Fi 与精简插件，保留 passwall & passwall2 & openclash，去除 ssr-plus） ================
        #

        # 目标平台（保留 workflow 原始的 ARMv8 通用设置）
        cat >> .config <<EOF
        CONFIG_TARGET_armsr=y
        CONFIG_TARGET_armsr_armv8=y
        CONFIG_TARGET_armsr_armv8_DEVICE_generic=y
        CONFIG_TARGET_ARCH_PACKAGES="aarch64_generic"
        CONFIG_DEFAULT_TARGET_OPTIMIZATION="-Os -pipe -mcpu=generic"
        CONFIG_CPU_TYPE="generic"
        EOF

        # 镜像设置（减少输出物）
        cat >> .config <<EOF
        CONFIG_TARGET_ROOTFS_TARGZ=y
        CONFIG_TARGET_ROOTFS_INITRAMFS=n
        CONFIG_TARGET_ROOTFS_CPIOGZ=n
        CONFIG_TARGET_ROOTFS_EXT4FS=n
        CONFIG_TARGET_ROOTFS_SQUASHFS=n
        EOF

        # 加快编译
        cat >> .config <<EOF
        CONFIG_DEVEL=y
        CONFIG_CCACHE=y
        EOF

        # USB 基础支持（保留常用项）
        cat >> .config <<EOF
        CONFIG_PACKAGE_kmod-usb-core=y
        CONFIG_PACKAGE_kmod-usb-dwc2=y
        CONFIG_PACKAGE_kmod-usb-dwc3=y
        CONFIG_PACKAGE_kmod-usb-ehci=y
        CONFIG_PACKAGE_kmod-usb-storage=y
        CONFIG_PACKAGE_kmod-usb-storage-extras=y
        CONFIG_PACKAGE_kmod-usb-storage-uas=y
        CONFIG_PACKAGE_kmod-usb-xhci-hcd=y
        CONFIG_PACKAGE_kmod-usb-ohci=y
        CONFIG_PACKAGE_kmod-usb2=y
        CONFIG_PACKAGE_kmod-usb3=y
        # 兼容 config.txt 的 usb2/usb-hid/net
        CONFIG_PACKAGE_kmod-usb-hid=y
        CONFIG_PACKAGE_kmod-usb-net=y
        EOF

        # IPv6 支持（参考两份配置：保留 ip6tables 及 helper）
        cat >> .config <<EOF
        CONFIG_PACKAGE_ip6tables=y
        CONFIG_PACKAGE_ip6tables-extra=y
        CONFIG_PACKAGE_ip6tables-mod-nat=y
        CONFIG_PACKAGE_ipv6helper=y
        CONFIG_PACKAGE_6in4=y
        EOF

        # Wi‑Fi 驱动：从 config.txt 拷贝的 Broadcom 支持与工具（针对需要 brcmfmac 的设备）
        cat >> .config <<EOF
        CONFIG_PACKAGE_kmod-brcmfmac=y
        CONFIG_BRCMFMAC_SDIO=y
        CONFIG_PACKAGE_kmod-brcmutil=y
        CONFIG_PACKAGE_kmod-cfg80211=y
        CONFIG_PACKAGE_kmod-mac80211=y
        CONFIG_PACKAGE_hostapd-common=y
        CONFIG_PACKAGE_wpa-cli=y
        CONFIG_PACKAGE_wpad-basic=y
        CONFIG_PACKAGE_iw=y
        EOF

        # LuCI / 网络相关插件（参考 config.txt 并保留 passwall、passwall2、openclash）
        cat >> .config <<EOF
        CONFIG_PACKAGE_luci-app-passwall=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Client=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Rust_Server=y
        CONFIG_PACKAGE_luci-app-passwall2=y
        CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Client=y
        CONFIG_PACKAGE_luci-app-passwall2_INCLUDE_Shadowsocks_Rust_Server=y
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-dockerman=y
        CONFIG_PACKAGE_luci-app-samba4=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        CONFIG_PACKAGE_luci-app-frpc=y
        CONFIG_PACKAGE_luci-app-mosdns=y
        CONFIG_PACKAGE_luci-app-alist=y
        CONFIG_PACKAGE_luci-app-argon-config=y
        CONFIG_PACKAGE_luci-theme-argon=y
        # 保留 luci 基础 httpd
        CONFIG_PACKAGE_luci-app-uhttpd=y
        EOF

        # 保持不启用的项（避免重复或体积过大），按需可以开启
        cat >> .config <<EOF
        # 这些大型或重复的组件默认不启用（可按需打开）
        # CONFIG_PACKAGE_luci-app-vsftpd is not set
        # CONFIG_PACKAGE_luci-app-upnp is not set
        EOF

        # DDNS：参考 config.txt，默认不启用内置 ddns-scripts（若需要请手动开启）
        cat >> .config <<EOF
        # CONFIG_PACKAGE_luci-app-ddns is not set
        # CONFIG_PACKAGE_ddns-scripts is not set
        EOF

        # 必备与磁盘工具（保留以便 NAS/存储功能）
        cat >> .config <<EOF
        CONFIG_PACKAGE_perl=y
        CONFIG_PACKAGE_perl-http-date=y
        CONFIG_PACKAGE_perlbase-file=y
        CONFIG_PACKAGE_perlbase-getopt=y
        CONFIG_PACKAGE_perlbase-time=y
        CONFIG_PACKAGE_perlbase-unicode=y
        CONFIG_PACKAGE_perlbase-utf8=y
        CONFIG_PACKAGE_blkid=y
        CONFIG_PACKAGE_fdisk=y
        CONFIG_PACKAGE_lsblk=y
        CONFIG_PACKAGE_parted=y
        CONFIG_PACKAGE_attr=y
        CONFIG_PACKAGE_btrfs-progs=y
        CONFIG_BTRFS_PROGS_ZSTD=y
        CONFIG_PACKAGE_chattr=y
        CONFIG_PACKAGE_dosfstools=y
        CONFIG_PACKAGE_e2fsprogs=y
        CONFIG_PACKAGE_f2fs-tools=y
        CONFIG_PACKAGE_f2fsck=y
        CONFIG_PACKAGE_lsattr=y
        CONFIG_PACKAGE_mkf2fs=y
        CONFIG_PACKAGE_xfs-fsck=y
        CONFIG_PACKAGE_xfs-mkfs=y
        CONFIG_PACKAGE_bsdtar=y
        CONFIG_PACKAGE_pigz=y
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_gawk=y
        CONFIG_PACKAGE_getopt=y
        CONFIG_PACKAGE_losetup=y
        CONFIG_PACKAGE_tar=y
        CONFIG_PACKAGE_uuidgen=y
        CONFIG_PACKAGE_ntfs3-mount=y
        CONFIG_PACKAGE_coreutils=y
        CONFIG_PACKAGE_coreutils-base64=y
        CONFIG_PACKAGE_coreutils-nohup=y
        CONFIG_PACKAGE_jq=y
        CONFIG_PACKAGE_pv=y
        EOF

        # 其它常用工具与服务（根据 config.txt）
        cat >> .config <<EOF
        CONFIG_PACKAGE_htop=y
        CONFIG_PACKAGE_iperf3=y
        CONFIG_PACKAGE_nano-plus=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_snmpd=y
        CONFIG_PACKAGE_vim-fuller=y
        CONFIG_PACKAGE_zsh=y
        EOF

        # 主题/UI 支持（保留 design/argon 可选）
        cat >> .config <<EOF
        CONFIG_PACKAGE_luci-theme-design=y
        CONFIG_PACKAGE_luci-app-design-config=y
        CONFIG_PACKAGE_luci-theme-netgear=y
        EOF

        # 清理行首空格并生成默认配置
        sed -i 's/^[ \t]*//g' ./.config
        make defconfig
